//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveAgency.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Orders = new HashSet<Orders>();
            this.ResurrectionHistory = new HashSet<ResurrectionHistory>();
        }
    
        public int ClientID { get; set; }
        public string FullName { get; set; }
        public bool IsAlive { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> RegisteredBy { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<ResurrectionHistory> ResurrectionHistory { get; set; }
    }
}
