//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveAgency.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public string Action { get; set; }
        public string TableAffected { get; set; }
        public Nullable<int> RecordID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
