//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveAgency.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Necromancers
    {
        public Necromancers()
        {
            this.ResurrectionHistory = new HashSet<ResurrectionHistory>();
        }
    
        public int NecromancerID { get; set; }
        public int UserID { get; set; }
        public string FullName { get; set; }
        public int ExperienceYears { get; set; }
        public string Phone { get; set; }
        public System.DateTime HireDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<ResurrectionHistory> ResurrectionHistory { get; set; }
    }
}
