//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveAgency.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.ResurrectionHistory = new HashSet<ResurrectionHistory>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Status { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ResurrectionHistory> ResurrectionHistory { get; set; }
    }
}
