//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraveAgency.Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResurrectionHistory
    {
        public int ResurrectionID { get; set; }
        public int ClientID { get; set; }
        public int NecromancerID { get; set; }
        public int OrderID { get; set; }
        public Nullable<System.DateTime> ResurrectionDate { get; set; }
        public bool Success { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Necromancers Necromancers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
